 [font.normal]
  family = "Iosevka"
  style = "Extended"

  [window]
  decorations = "none"
  opacity = 1

  blur = true

  [general]
  import = ["~/.config/alacritty/themes/themes/kanagawa_wave.toml"]
  # import = ["~/.config/alacritty/themes/themes/kanagawa_dragon.toml"]
