---
- name: Install dotfiles
  hosts: localhost
  connection: local
  vars:
    symlinks:
      - { src: "cargo/config.toml", dest: "~/.cargo/config.toml" }
      - { src: "fish", dest: "~/.config/fish" }
      - { src: "nvim", dest: "~/.config/nvim" }
      - { src: "gitui/vim_style_key_config.ron", dest: "~/.config/gitui/key_bindings.ron" }
      - { src: "zellij", dest: "~/.config/zellij" }
      - { src: "tmuxp", dest: "~/.tmuxp" }
      - { src: "tmux.conf", dest: "~/.tmux.conf" }
      - { src: "stylua.toml", dest: "~/.config/stylua.toml" }
      - { src: "nushell/config.nu", dest: "~/.config/nushell/config.nu" }
      - { src: "nushell/rtx.nu", dest: "~/.config/nushell/rtx.nu" }
      - { src: "nushell/aliases.nu", dest: "~/.config/nushell/aliases.nu" }
      - { src: "starship.toml", dest: "~/.config/starship.toml" }
  tasks:
    - name: Creating symlinks
      ansible.builtin.file:
        src: "{{ playbook_dir }}/{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ symlinks }}"
